/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '15-7-16 下午4:15' with Gradle 2.4
 *
 * @author Administrator, @date 15-7-16 下午4:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
